version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package

workflows:
  build-and-test-project:
    jobs:
      - build
